import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HourlyForecastProvider } from '@/context/ForecastContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Soil Moisture',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
  rel="icon"
  href="/soil.png"
  type="image/<generated>"
  sizes="<generated>"
/>
      <body className={inter.className}>
        <HourlyForecastProvider>{children}</HourlyForecastProvider>
      </body>
    </html>
  );
}
